const List<Map<String, String>> eventsList = [
  {'event': "Mariage"},
  {'event': "Anniversaire"},
  {'event': "Baptême"},
  {'event': "Fête de naissance"},
  {'event': "Fête de fiançailles"},
  {'event': "Réunion de famille"},
  {'event': "Soirée de gala"},
  {'event': "Soirée à thème"},
  {'event': "Cérémonie de remise des diplômes"},
  {'event': "Pendaison de crémaillère"},
  {'event': "Baby shower"},
  {'event': "Enterrement de vie de jeune fille/garçon"},
  {'event': "Réception d'entreprise"},
  {'event': "Soirée de retraite"},
  {'event': "Célébration de Noël"},
  {'event': "Fête de fin d'année"},
  {'event': "Festival"},
  {'event': "Spectacle de danse"},
  {'event': "Concert"},
  {'event': "Conférence"},
];
